// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.notificationhubs.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.util.List;
import java.util.Map;

/** Represents an Web Push based Azure Notification Hubs Installation. */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "platform")
@JsonTypeName("browser")
@Fluent
public final class BrowserInstallation extends Installation {
    /*
     * The Web API push handle for the installation
     */
    @JsonProperty(value = "pushHandle", required = true)
    private BrowserPushHandle pushHandle;

    /**
     * Creates an instance of BrowserInstallation class.
     *
     * @param tags the tags value to set.
     * @param templates the templates value to set.
     * @param pushHandle the pushHandle value to set.
     */
    @JsonCreator
    public BrowserInstallation(
            @JsonProperty(value = "tags", required = true) List<String> tags,
            @JsonProperty(value = "templates", required = true) Map<String, String> templates,
            @JsonProperty(value = "pushHandle", required = true) BrowserPushHandle pushHandle) {
        super(tags, templates);
        this.pushHandle = pushHandle;
    }

    /**
     * Get the pushHandle property: The Web API push handle for the installation.
     *
     * @return the pushHandle value.
     */
    public BrowserPushHandle getPushHandle() {
        return this.pushHandle;
    }

    /** {@inheritDoc} */
    @Override
    public BrowserInstallation setUserId(String userId) {
        super.setUserId(userId);
        return this;
    }
}
