// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.notificationhubs.models;

import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/** Represents a Web Push push handle. */
@Immutable
public final class BrowserPushHandle {
    /*
     * The Web Push API endpoint
     */
    @JsonProperty(value = "endpoint", required = true)
    private String endpoint;

    /*
     * The Web Push API P256DH key
     */
    @JsonProperty(value = "p256dh", required = true)
    private String p256dh;

    /*
     * The Web Push API auth secret
     */
    @JsonProperty(value = "auth", required = true)
    private String auth;

    /**
     * Creates an instance of BrowserPushHandle class.
     *
     * @param endpoint the endpoint value to set.
     * @param p256dh the p256dh value to set.
     * @param auth the auth value to set.
     */
    @JsonCreator
    public BrowserPushHandle(
            @JsonProperty(value = "endpoint", required = true) String endpoint,
            @JsonProperty(value = "p256dh", required = true) String p256dh,
            @JsonProperty(value = "auth", required = true) String auth) {
        this.endpoint = endpoint;
        this.p256dh = p256dh;
        this.auth = auth;
    }

    /**
     * Get the endpoint property: The Web Push API endpoint.
     *
     * @return the endpoint value.
     */
    public String getEndpoint() {
        return this.endpoint;
    }

    /**
     * Get the p256dh property: The Web Push API P256DH key.
     *
     * @return the p256dh value.
     */
    public String getP256dh() {
        return this.p256dh;
    }

    /**
     * Get the auth property: The Web Push API auth secret.
     *
     * @return the auth value.
     */
    public String getAuth() {
        return this.auth;
    }
}
