// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/** Package containing the data models for NotificationHubs. The Azure Notification Hubs service. */
package com.notificationhubs.models;
