# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import BrowserInstallation
from ._models import BrowserPushHandle
from ._models import FcmLegacyInstallation
from ._models import Installation
from ._models import JsonPatch

from ._enums import ContentTypeType
from ._enums import ContentTypeType
from ._enums import JsonPatchOperation
from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "BrowserInstallation",
    "BrowserPushHandle",
    "FcmLegacyInstallation",
    "Installation",
    "JsonPatch",
    "ContentTypeType",
    "ContentTypeType",
    "JsonPatchOperation",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
