# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from enum import Enum
from azure.core import CaseInsensitiveEnumMeta


class ContentTypeType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of ContentTypeType."""

    APPLICATION / JSON
    CHARSET = UTF_8 = "application/json;charset=utf-8"
    APPLICATION / XML
    CHARSET = UTF_8 = "application/xml;charset=utf-8"
    APPLICATION / OCTET_STREAM = "application/octet-stream"


class ContentTypeType(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Type of ContentTypeType."""

    APPLICATION / JSON
    CHARSET = UTF_8 = "application/json;charset=utf-8"
    APPLICATION / XML
    CHARSET = UTF_8 = "application/xml;charset=utf-8"
    APPLICATION / OCTET_STREAM = "application/octet-stream"


class JsonPatchOperation(str, Enum, metaclass=CaseInsensitiveEnumMeta):
    """Represents a JSON Patch operation type."""

    ADD = "add"
    """The add JSON patch operation type"""
    REMOVE = "remove"
    """The remove JSON patch operation type"""
    REPLACE = "replace"
    """The replace JSON patch operation type"""
